// <auto-generated />
namespace SpinWheel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdddboListClientAward : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdddboListClientAward));
        
        string IMigrationMetadata.Id
        {
            get { return "202204210957187_Add-dbo.ListClientAward"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
