// <auto-generated />
namespace SpinWheel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixSomeToAwardClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixSomeToAwardClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202301040955172_FixSomeToAwardClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
